# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cce9b20afc891c8c17e45eee256aee375be05e6ff3c98a22382ae0bb1458f83041e1f29645c783febc81b9bfa220b63e4cd308300e4b1dd1937adf5c07c00e6c

test:
  secret_key_base: 9541493b45e64780a1348d8b042ed3e25a48fe4fe5383d1815e0f0f5c445435174b7d28a68025ce5475eddce32393fc7a9a5fe9c237603d99d324f69e50506dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
